version: "3"
services:
  front:
    image: ghcr.io/jojo-05/kitchenowl-web:recipe-import
    build:
      context: ./kitchenowl
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8027:80"
    environment:
      - MAX_CONTENT_LENGTH_MB=2048
    depends_on:
      - back
  back:
    image: ghcr.io/jojo-05/kitchenowl-backend:recipe-import
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - JWT_SECRET_KEY=a5kAjs5duiQ5whIdh145asdG86wdgh4erg
      - MAX_CONTENT_LENGTH_MB=2048
      - FRONT_URL=http://localhost
    volumes:
      - kitchenowl_data:/data

volumes:
  kitchenowl_data: